name: Docker CI Ubuntu

on:
  push:
    branches: [ main, gha-testing ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.github/renovate.json5'
      - '.github/CODEOWNERS'
      - 'LICENSE'
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
      DO_NOT_TRACK: 1
      # Used in the earthly/actions-setup github action
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: earthly/actions-setup@main
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: start registry
        run: docker run -d -p 5000:5000 --name registry registry:3.0
      - name: warm the registry
        run: sleep 10 && docker logs registry && ls -la && ./reg-test.sh
      - name: lint
        run: earthly +lint
      - name: disable network (all resources should be preloaded by now)
        run: sudo ufw default deny outgoing && sudo ufw enable
      - name: lint again
        run: earthly +lint
      - name: Buildkit logs (runs on failure)
        run: docker logs earthly-buildkitd
        if: ${{ failure() }}
