name: Docker CI Ubuntu

on:
  push:
    branches: [ main, gha-testing ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.github/renovate.json5'
      - '.github/CODEOWNERS'
      - 'LICENSE'
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
      DO_NOT_TRACK: 1
      # Used in the earthly/actions-setup github action
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: earthly/actions-setup@main
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: cgroup stuff
        run: test -f /sys/fs/cgroup/cgroup.controllers
      #- name: +for-linux
      #  run: earthly +lint #for-linux
      - name: cgrouppppp
        run: sudo ufw default deny outgoing && sudo ufw enable
      - name: again
        run: echo hello && earthly +lint #for-linux
      - name: Buildkit logs (runs on failure)
        run: docker logs earthly-buildkitd
        if: ${{ failure() }}
