name: ido-test

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: +lint-docs
    runs-on: "ubuntu-latest"
    env:
      FORCE_COLOR: 1
      # Used in our github action as the token - TODO: look to change it into an input
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: earthly/actions-setup@main
      - name: Execute lint
        run: earthly --ci -P +lint-docs
